### PR TITLE
Add support for Composer 2

### PR DESCRIPTION
**Pull request by emodric**

### CODE REVIEW

**Comment by emodric** [comment]
The plugin has issues with canonical repos it seems. It's a chicken/egg situation.

When the plugin adds the path repo to Composer 2, it treats it as a canonical repo, which means that usecases where a package with required version cannot be found in path (e.g. different versions - `composer.json` requires 1.2 for one of the packages, but symlinked version is in 1.3), the install will fail and will not fallback to fetching those packages from `packagist.org`. In Composer 2, it would simply install those packages in 1.2 from `packagist.org`, and the rest would be symlinked.

If we set the repo to be non-canonical, then it seems that the repo is simply ignored, since the valid version (be it e.g. `1.3.0`, `1.3.0@dev`, `dev-1.3.x`, `dev-master`) exists on `packagist.org` and the path repo will simply be ignored.

**Comment by keichinger** [comment]
@franzliedke is there any way that the community can help you out in getting this PR merged and released? :-)

**Comment by irazasyed** [comment]
Hey @franzliedke, could you spare a few min and please merge this PR? That would be appreciated :)

**Comment by roni-estein** [comment]
I've noticed this project is now marked abandoned in my setup. I have this as a dependency. Perhaps you can allow someone to take it over or someone who is willing can fork it if there is no response.

**Comment by franzliedke** [comment]
Hello folks. I'm happy about the interest in keeping this maintained.

Is anybody interested in pairing on this, e.g. on Friday?

@roni-estein Can you share where this is marked as abandoned? Or are you referring to the [Composer CLI warning](https://github.com/franzliedke/studio/issues/101#issuecomment-719602737)?

**Comment by apfelbox** [comment]
Yeah! 🎉 

@franzliedke I would be willing help out with maintenance and development, if you need any help!

**Comment by arnehendriksen** [comment]
@franzliedke please merge this PR, it's the only thing keeping me (and probably others) from updating Composer to 2.0

**Comment by roni-estein** [comment]
> Hello folks. I'm happy about the interest in keeping this maintained.
> 
> Is anybody interested in pairing on this, e.g. on Friday?
> 
> @roni-estein Can you share where this is marked as abandoned? Or are you referring to the [Composer CLI warning](https://github.com/franzliedke/studio/issues/101#issuecomment-719602737)?

Yes, it was the CLI warning, sorry I missed this earlier. I've started removing it from my projects I misunderstood the warning. I didn't realize composer would give that alert without the actual project being abandoned.

**Comment by vikingmaster** [comment]
This is an amazing package, we want this! :)
Composer 2 gets supported for this package, I am sending some support donation to the maintainer.
Support for support it is :)

**Comment by franzliedke** [comment]
@emodric Thanks very much - I will release a new version with this shortly. (Currently also doing some other cleanup, with the help of @apfelbox.)

Regarding the problem with canonical repositories you mentioned: it seems to boil down to a combination of a repository that's both present in a local path and on Packagist, and a mismatch between your version constraint and the local version, right? Please open a new issue with minimal reproduction steps! :pray: I can't stop thinking that my experimental approach from [this release](https://github.com/franzliedke/studio/releases/tag/0.14.0-beta1) is the way to go.

@vikingmaster Feel free to support me via GitHub Sponsors or https://paypal.me/franzliedke. :wink:

**Comment by vikingmaster** [comment]
Big thank you. 
Support package sent :)

**Comment by franzliedke** [comment]
Relased in [version 0.15.0](https://github.com/franzliedke/studio/releases/tag/0.15.0). Please update and let me know if you encounter any problems.

**Comment by emodric** [comment]
Thanks @franzliedke  for merging !

As for my issue with canonical repos, yes, it happens when there's a mismatch in versions specified in `composer.json` and versions checked out in local path repo. I will try to create a minimal reproducer :+1:

**Comment by emodric** [comment]
@franzliedke Here are the two reproducers for two issues noted above:

https://github.com/franzliedke/studio/issues/108

**Pull request merged**
