### PR TITLE
Additions to README regarding usage workflow

### PR DESCRIPTION
**Pull request by rask**
Add a section about the general workflow when using studio
to develop packages.

Refs #60.

### CODE REVIEW

**Comment by rask** [comment]
Please let me know if I got some technicalities wrong. :)

**Comment by franzliedke** [comment]
Wow, thank you!

Almost perfect, just one tiny thing. If you're inside a directory with a composer.json, `studio create` will automatically execute `sutdio load`, so part of your explanation is superfluous...

**Comment by rask** [comment]
Oh I didn't realize that. I'll update this as soon as possible!

**Comment by franzliedke** [comment]
Hey @rask, thank you so much for your pull. Will you find some time to update it soon?
I haven't had much time for Studio either, unfortunately. But I'm currently looking into changing that, so I'd love to merge this. :)

**Comment by franzliedke** [comment]
Oh, you know what? I can just take care of it myself. ;)

Thank you so much for your initiative! :heart:

**Pull request merged**
