### PR TITLE
Use more recent PHPUnit and PHPSpec versions

### PR DESCRIPTION
**Pull request by Arcesilas**
PHPUnit: use 6.3 instead of 4.0
PHPSpec: use 4.0 instead of 2.0

### CODE REVIEW

**Comment by Arcesilas** [comment]
By the way, it would be nice to use the latest version (without hard coding version number) or let users specify version of their choice. What do you think ?

**Comment by Arcesilas** [comment]
PHPSpec dropped HHVM support (https://github.com/phpspec/phpspec/issues/1139). If HHVM is really required to be supported by Studio, you might consider dropping PHPSpec dependency.

**Comment by franzliedke** [comment]
*Did* PHPSpec drop support already, or are they considering it? (The link looks more like the latter.)

**Comment by franzliedke** [comment]
Anyway, thanks for the merge!

We could implement HHVM support as an additional part (with an additional question) that would then add this line to the travis.yml file...

**Comment by franzliedke** [comment]
Released in v0.12.0. Thanks again!

**Comment by Arcesilas** [comment]
They dropped hhvm support on Dec 29, 2016: https://github.com/phpspec/phpspec/commit/ddccee611f3fd69dfabe4528a03c39d2e7c15717#diff-354f30a63fb0907d4ad57269548329e3

**Pull request merged**
