### PR TITLE
Allow install on Symfony 4.0

### PR DESCRIPTION
**Pull request by emodric**
This would allow running my CI builds on Symfony 4 :)

### CODE REVIEW

**Comment by emodric** [comment]
Tag would also be appreciated :)

**Comment by franzliedke** [comment]
Thanks a lot, it's appreciated!
One quick question, though: did you check for any compatibility problems?

Release will follow, I will let you know here.

**Comment by emodric** [comment]
Thanks!

I went quickly through the code to see if there are any deprecated features being used, like `ProcessBuilder`.

**Comment by franzliedke** [comment]
Released as part of [version 0.13.0](https://github.com/franzliedke/studio/releases/tag/0.13.0).

**Pull request merged**
