### PR TITLE
Allow Symfony 5.0

### PR DESCRIPTION
**Pull request by emodric**

### CODE REVIEW

**Comment by franzliedke** [comment]
Thanks a lot!

**Comment by simonberger** [comment]
@emodric @franzliedke It seems not to be compatible to symfony 5 though

`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given`

https://github.com/symfony/symfony/blob/5.0/UPGRADE-5.0.md#process

**Comment by emodric** [comment]
Doh! When I tested the package, I somehow didn't notice that I was using Symfony 4.4 instead of 5.0, so there were no issues :/

What would be the best way to fix this? Some form of version detection? The new syntax was introduced in Symfony 3.3 I believe.

**Comment by franzliedke** [comment]
@emodric @simonberger That problem only occurred within `studio create`, right? That now works with Symfony 5 [after this commit](https://github.com/franzliedke/studio/commit/e866e643f50bfaadb70847f38ee58ddd3ab62300).

This has been relased in [version 0.15.0](https://github.com/franzliedke/studio/releases/tag/0.15.0).

**Comment by simonberger** [comment]
I absolutely don't remember what I did back then 😎

**Comment by emodric** [comment]
I don't really remember either 😆

**Pull request merged**
