### PR TITLE
Suggest adding ~/.composer/vendor/bin to PATH

### PR DESCRIPTION
**Pull request by RemiCollin**

### CODE REVIEW

**Comment by franzliedke** [comment]
Great, thank you!

**Comment by RemiCollin** [comment]
Welcome! And BTW thanks for this great package, was really looking for something like this to come up !

**Comment by franzliedke** [comment]
Glad you like it. The next release will only get better. =)

How are you using it right now?

**Comment by RemiCollin** [comment]
Well so far so good, just created a first package 5 minutes ago.

**Pull request merged**
