### PR TITLE
Allow Symfony 6.0

### PR DESCRIPTION
**Pull request by D3lph1**

### CODE REVIEW

**Comment by franzliedke** [comment]
@D3lph1 Thanks a lot! Have you checked the APIs we use for compatibility?

**Comment by D3lph1** [comment]
No, I have not yet. I've just checked that my library was included properly. Is there any contributing guide for that?

**Comment by franzliedke** [comment]
Nope. We'll have to look at the code and all usages of `Symfony\*` classes. 😉

**Comment by franzliedke** [comment]
Thanks a lot!

**Comment by apfelbox** [comment]
I released `0.16.0` containing this fix today.

**Pull request merged**
